### ISSUE TITLE
Error in changing download Directory

### ISSUE THREAD

**Issue by NoahPM** [EldinZenderink/LittleWeeb#3]
When I attempt to change the download directory by clicking the select button, this error comes up in the console:
`Unhandled Exception: System.IO.FileNotFoundException: Could not load file or assembly 'Microsoft.WindowsAPICodePack.Shell, Version=1.1.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35' or one of its dependencies. The system cannot find the file specified.
   at LittleWeebIRC.Program.setDlDir()
   at System.Threading.ThreadHelper.ThreadStart_Context(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()`
and then the app crashes. Setting it manually via the text input doesn't work either. Help?

P.S. Any plans to add a multi-select feature? It gets tiring clicking on 26 different checkboxes to download a season :p. Thanks for all your work!

**Comment by EldinZenderink** [comment]
Oh crap, might have forgotten to add the right dll for that... will fix asap, and yes, multi select is on my wishlist as well :)

**Comment by NoahPM** [comment]
Thanks, the .dll works, though the location it gets changed to is reset to the default if the app is closed.

**Comment by EldinZenderink** [comment]
Please test it out for me :) I hope that it's fixed now in the little time that I had.
